import type { Metadata } from "next";

import "./globals.css";
import ConditionalNav from "@/component/ClientComponents/Conditionalshow";
import ConditionalFooter from "@/component/ClientComponents/ConditionalshowFooter";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ConditionalNav />
        <Toaster />
        {children}
        <ConditionalFooter />
      </body>
    </html>
  );
}
