import type { Metadata } from "next";

import "./globals.css";
// import Nav from "@/component/ClientComponents/Nav";
import ConditionalNav from "@/component/ClientComponents/Conditionalshow";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ConditionalNav />
        {children}
      </body>
    </html>
  );
}
